### ISSUE TITLE
When will the training code release?

### ISSUE THREAD

**Issue by dk-liang** [cvlab-stonybrook/DM-Count#1]
Thanks to the authors. I have read the paper, and I think it is excellent work. However,  the training and OT code are not provided, which is difficult to follow the work.

**Comment by harryliew** [comment]
> Thanks to the authors. I have read the paper, and I think it is excellent work. However, the training and OT code are not provided, which is difficult to follow the work.

Thanks for your interest Liang! We will release all the code in the next few weeks.

**Comment by Boyu-Wang** [comment]
Hi dkliang,

The training code and OT computation code has been updated. Thanks for your interest!
