### ISSUE TITLE
Why not use more advanced backbone

### ISSUE THREAD

**Issue by hhk123** [cvlab-stonybrook/DM-Count#15]
Excellent work!
But why not use more advanced backbone, such as resnet or CSPNet et.?
Is that because of in order to prove the progresiveness of the loss designed?

**Comment by Boyu-Wang** [comment]
Hi, 
Thank you for your attention to our work! For fair comparisons, we use the same backbone network as other losses. You are welcome to replace the backbone with other state-of-the-art networks.

**Comment by hhk123** [comment]
> Hi,
> Thank you for your attention to our work! For fair comparisons, we use the same backbone network as other losses. You are welcome to replace the backbone with other state-of-the-art networks.

I see.Thank you and happy Chiness new year!

**Comment by Hasan-Torabi** [comment]
@hhk123 Hi, Good idea.
Have you tried using other backbones?
