### ISSUE TITLE
The OT loss is too small.Dose it work?

### ISSUE THREAD

**Issue by hhk123** [cvlab-stonybrook/DM-Count#16]
It's even less than 0:
Epoch 46 Train, Loss: 3.89, OT Loss: -6.02e-07, Wass Distance: 803.41, OT obj value: 113.64, Count Loss: 3.55, TV Loss: 0.35, MSE: 8.88 MAE: 3.55, Cost 24.5 sec

**Comment by Boyu-Wang** [comment]
Different losses should not be compared directly. The OT loss and other losses are not computed in the same way. In multi-loss training, what matters is the gradient contribution of each loss component. The OT loss here is basically computed as the sum of Grad_from_OT * parameters.
