### ISSUE TITLE
About density map

### ISSUE THREAD

**Issue by simaiden** [cvlab-stonybrook/DM-Count#5]
Hi, thanks for your amazing work!
I have a question about the density maps estimation. In the paper, your mentioned that didn't use precalculated density maps for ground truth annotations because of the hurt in generalization performance, so only use points annotations right? But after, i got lose because in the toy problem you said "he source density map ˆz is initialized from a uniform distribution between 0 and 0.01", and also in preprocess datasets scripts you calculate a gaussian density map. 

So the doubt is if you need a precalculated density map, and in this case how can i calculate in the way you do.

Thanks!

**Comment by Boyu-Wang** [comment]
The gaussian density maps are generated in the preprocessing steps. They are not used in the training. You could check the data loader and loss computation for more details. We treat the binary annotation map as target distribution and compute distribution distance between predicted density map (source distribution) and target distribution.

**Comment by simaiden** [comment]
> The gaussian density maps are generated in the preprocessing steps. They are not used in the training. You could check the data loader and loss computation for more details. We treat the binary annotation map as target distribution and compute distribution distance between predicted density map (source distribution) and target distribution.

Many thanks! I was checking the code and realize exactly what you said.
